language: generic

cache:
  directories:
    - $HOME/.stack

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version

script:
  - stack build
  - stack install
  - stack test

matrix:
  include:
   - os: linux
   - os: osx

before_deploy:
  - mv "$(which qhs)" .
  - zip qhs_"$(uname | awk '{ print tolower($0) }')".zip qhs

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UPex1F6p1m2L+IPyZyr92b74IiwIQFA3FVN1/Cj3yAj5x42O18dftmVrBny7ELB3pEROfyVunpbe0dRNkJqo2OWpUQ1lLBpfGROIXlHR8Cb+2B8EIgZ0XSB4PISJoFJnJl1unaV2aVaL0/Cj1si9XxVnmBXglayIBBHUZ06QKHpnXCp+8zXwqw6LeGeW2CYUTpGIVagMQL7XSuqz9U8QZSv1V134HP3YlJsoPD9p5YUSrOp44Ku/lEg6fAjtoFg7/YgroQ4z2+CnwfP5auRFDJnN0uJw8UUDXzWF7Wq9Qa0kOn+lmwGHazLsA/JX0yfFICLoEU6i5BOdR4X9J8FExbfTXjrSM2a1wDHxngBWK1+m7ukn44gti2K/lybDBCKUFnl0h+hRqcxpkzvX48pRtXJSYF3AifKAvZyZdjseOLvwPKcq1O81uv8Dyh3r1akUiH7ehjWNtngCKptqtmEtUa1XGV3pBFjFpqRqywuappdREsvEKiQ6wFnPdqxn5AqDFMWhgkCdIFS0Lapr6YhWo/mzeMl/+boWb8+s4skz8kEhmsPSXtL+OofXwIEwF9rrAy7gSHFwckMAjhEr6m92st13OUY4HWWHryJI6Sy1xum9kv5q4offM6TIizdNQ26NzYUCHaeYb0jlMitqXHLIZTEcrkzQSSlCEGDGCCyrbVw=
  file: ./*.zip
  file_glob: true
  on:
    repo: itchyny/qhs
    tags: true
    all_branches: false
